env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

sudo: false
language: ruby
cache: bundler

before_install:
  - gem update bundler
  
before_script:
  - bundle update

script:
  - bundle exec rspec

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-head
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

  fast_finish: true

